export interface ClubBlueprint {
  id: string;
  name: string;
  shortName: string;
  city: string;
  primaryColor: string;
  secondaryColor: string;
  reputation: number;
  fanbase: number;
}

export const CLUB_BLUEPRINTS: readonly ClubBlueprint[] = [
  {
    id: "rubro-rio",
    name: "Rubro Rio",
    shortName: "RRO",
    city: "Rio de Janeiro",
    primaryColor: "#D93A3A",
    secondaryColor: "#101010",
    reputation: 91,
    fanbase: 96,
  },
  {
    id: "alviverde-sp",
    name: "Alviverde SP",
    shortName: "AVP",
    city: "Sao Paulo",
    primaryColor: "#1E8F4D",
    secondaryColor: "#F5F5F5",
    reputation: 90,
    fanbase: 91,
  },
  {
    id: "tricolor-paulista",
    name: "Tricolor Paulista",
    shortName: "TCP",
    city: "Sao Paulo",
    primaryColor: "#D72638",
    secondaryColor: "#FFFFFF",
    reputation: 84,
    fanbase: 88,
  },
  {
    id: "alvinegro-paulista",
    name: "Alvinegro Paulista",
    shortName: "AVN",
    city: "Sao Paulo",
    primaryColor: "#111111",
    secondaryColor: "#FFFFFF",
    reputation: 82,
    fanbase: 90,
  },
  {
    id: "celeste-mineiro",
    name: "Celeste Mineiro",
    shortName: "CLM",
    city: "Belo Horizonte",
    primaryColor: "#2368D9",
    secondaryColor: "#FFFFFF",
    reputation: 81,
    fanbase: 78,
  },
  {
    id: "atletico-mineiro",
    name: "Atletico Mineiro",
    shortName: "ATM",
    city: "Belo Horizonte",
    primaryColor: "#151515",
    secondaryColor: "#FFFFFF",
    reputation: 87,
    fanbase: 86,
  },
  {
    id: "gremio-porto",
    name: "Gremio Porto",
    shortName: "GPO",
    city: "Porto Alegre",
    primaryColor: "#55A7E6",
    secondaryColor: "#111111",
    reputation: 82,
    fanbase: 80,
  },
  {
    id: "colorado-sul",
    name: "Colorado Sul",
    shortName: "COL",
    city: "Porto Alegre",
    primaryColor: "#D92D2D",
    secondaryColor: "#FFFFFF",
    reputation: 83,
    fanbase: 79,
  },
  {
    id: "tricolor-bahia",
    name: "Tricolor Bahia",
    shortName: "BAH",
    city: "Salvador",
    primaryColor: "#1E5AA8",
    secondaryColor: "#E3342F",
    reputation: 72,
    fanbase: 73,
  },
  {
    id: "leao-fortaleza",
    name: "Leao Fortaleza",
    shortName: "LEF",
    city: "Fortaleza",
    primaryColor: "#D72638",
    secondaryColor: "#1E5AA8",
    reputation: 76,
    fanbase: 70,
  },
  {
    id: "voz-ceara",
    name: "Voz Ceara",
    shortName: "VOZ",
    city: "Fortaleza",
    primaryColor: "#111111",
    secondaryColor: "#FFFFFF",
    reputation: 68,
    fanbase: 67,
  },
  {
    id: "furacao-curitiba",
    name: "Furacao Curitiba",
    shortName: "FCT",
    city: "Curitiba",
    primaryColor: "#B91C1C",
    secondaryColor: "#111111",
    reputation: 77,
    fanbase: 69,
  },
  {
    id: "coxa-curitiba",
    name: "Coxa Curitiba",
    shortName: "COX",
    city: "Curitiba",
    primaryColor: "#15803D",
    secondaryColor: "#FFFFFF",
    reputation: 66,
    fanbase: 64,
  },
  {
    id: "alvinegro-rio",
    name: "Alvinegro Rio",
    shortName: "ANR",
    city: "Rio de Janeiro",
    primaryColor: "#111111",
    secondaryColor: "#FFFFFF",
    reputation: 79,
    fanbase: 74,
  },
  {
    id: "cruz-rio",
    name: "Cruz Rio",
    shortName: "CRZ",
    city: "Rio de Janeiro",
    primaryColor: "#111111",
    secondaryColor: "#FFFFFF",
    reputation: 71,
    fanbase: 76,
  },
  {
    id: "tricolor-rio",
    name: "Tricolor Rio",
    shortName: "TRR",
    city: "Rio de Janeiro",
    primaryColor: "#7F1D1D",
    secondaryColor: "#166534",
    reputation: 80,
    fanbase: 77,
  },
  {
    id: "dragao-goiano",
    name: "Dragao Goiano",
    shortName: "DGO",
    city: "Goiania",
    primaryColor: "#DC2626",
    secondaryColor: "#111111",
    reputation: 64,
    fanbase: 55,
  },
  {
    id: "esmeralda-goias",
    name: "Esmeralda Goias",
    shortName: "ESG",
    city: "Goiania",
    primaryColor: "#15803D",
    secondaryColor: "#FFFFFF",
    reputation: 65,
    fanbase: 59,
  },
  {
    id: "aurinegro-criciuma",
    name: "Aurinegro Criciuma",
    shortName: "AUC",
    city: "Criciuma",
    primaryColor: "#FACC15",
    secondaryColor: "#111111",
    reputation: 62,
    fanbase: 52,
  },
  {
    id: "juventude-serra",
    name: "Juventude Serra",
    shortName: "JUS",
    city: "Caxias do Sul",
    primaryColor: "#16A34A",
    secondaryColor: "#FFFFFF",
    reputation: 61,
    fanbase: 50,
  },
];
